In [1]:
import warnings

warnings.filterwarnings("ignore")

import os
import re
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from rich import print
from tqdm import tqdm

In [2]:
def read_file_to_str_li(fp, print_exp=True):
    with open(fp, "r") as f:
        lines = f.read().split("\n")
    if print_exp:
        print(f"Read from {fp}:")
        print(f"First line: {lines[0]} | Last line: {lines[-1]}")
        print("-" * 6)

    return lines


# define the function blocks
def convert_to_int(input_str):
    if input_str == "" or input_str == " ":
        return None
    return int(input_str)


def convert_to_str(input_str):
    return str(input_str)


# map the inputs to the function blocks
converts = {
    "i": convert_to_int,
    "s": convert_to_str,
}


def convert_str_li_to_other_li(
    str_li, pattern="i", per_letter=False, sep=" ", start_row=0, end_row=None
):
    """ Convert a list of string to a list of other types
    
    pattern: a list of types for one item. 
        'i' for int, 's' for string
        'si' means: convert the 1st item to string, the rest to integer
        If separated items are more than pattern items,
        use the last one from the parttern.
    if per_letter=True, ignore sep and separate item per letter
    """
    target_str_li = str_li[start_row:end_row]
    # find max item num
    max_item_num = 1
    if per_letter:
        max_item_num = max([len(s) for s in target_str_li])
    else:
        max_item_num = max([len(s.split(sep)) for s in target_str_li])

    # extend the pattern to the max itme num
    pattern = (
        pattern + f"{pattern[-1]}" * (max_item_num - len(pattern))
        if max_item_num > len(pattern)
        else pattern
    )

    # convert
    if per_letter:
        return [
            [converts[pattern[idx]](item) for idx, item in enumerate(s)]
            for s in target_str_li
        ]
    else:
        if sep == " ":
            return [
                [converts[pattern[idx]](item) for idx, item in enumerate(s.split())]
                for s in target_str_li
            ]
        else:
            return [
                [converts[pattern[idx]](item) for idx, item in enumerate(s.split(sep))]
                for s in target_str_li
            ]

In [3]:
fp = "input.txt"
lines = read_file_to_str_li(fp)

print("Convert to:")

# head = convert_str_li_to_other_li(
#     lines, pattern="i", per_letter=False, sep=",", start_row=0, end_row=1
# )

# print(f"Head:\n{head}")

data = convert_str_li_to_other_li(
    lines, pattern="i", per_letter=False, sep=",", start_row=None, end_row=None
)

# data = convert_str_li_to_other_li(
#     lines, pattern="s", per_letter=False, sep=" -> ", start_row=None, end_row=None
# )
# data = convert_str_li_to_other_li(
#     lines, pattern="i", per_letter=False, sep=" ", start_row=2, end_row=None
# )
# data = convert_str_li_to_other_li(
#     lines, pattern="si", per_letter=False, sep=" ", start_row=0, end_row=None
# )
# data = convert_str_li_to_other_li(
#     lines, pattern="i", per_letter=True, sep=" ", start_row=0, end_row=None
# )

print(f"First line: {data[0]}")
print(f"Last line: {data[-1]}")
print("-" * 6)

Read from input.txt:

First line: 2,5,3,4,4,5,3,2,3,3,2,2,4,2,5,4,1,1,4,4,5,1,2,1,5,2,1,5,1,1,1,2,4,3,3,1,4,2,3,4,5
,1,2,5,1,2,2,5,2,4,4,1,4,5,4,2,1,5,5,3,2,1,3,2,1,4,2,5,5,5,2,3,3,5,1,1,5,3,4,2,1,4,4,5,4,5,3,
1,4,5,1,5,3,5,4,4,4,1,4,2,2,2,5,4,3,1,4,4,3,4,2,1,1,5,3,3,2,5,3,1,2,2,4,1,4,1,5,1,1,2,5,2,2,5
,2,4,4,3,4,1,3,3,5,4,5,4,5,5,5,5,5,4,4,5,3,4,3,3,1,1,5,2,4,5,5,1,5,2,4,5,4,2,4,4,4,2,2,2,2,2,
3,5,3,1,1,2,1,1,5,1,4,3,4,2,5,3,4,4,3,5,5,5,4,1,3,4,4,2,2,1,4,1,2,1,2,1,5,5,3,4,1,3,2,1,4,5,1
,5,5,1,2,3,4,2,1,4,1,4,2,3,3,2,4,1,4,1,4,4,1,5,3,1,5,2,1,1,2,3,3,2,4,1,2,1,5,1,1,2,1,2,1,2,4,
5,3,5,5,1,3,4,1,1,3,3,2,2,4,3,1,1,2,4,1,1,1,5,4,2,4,3 | Last line: 2,5,3,4,4,5,3,2,3,3,2,2,4,
2,5,4,1,1,4,4,5,1,2,1,5,2,1,5,1,1,1,2,4,3,3,1,4,2,3,4,5,1,2,5,1,2,2,5,2,4,4,1,4,5,4,2,1,5,5,3
,2,1,3,2,1,4,2,5,5,5,2,3,3,5,1,1,5,3,4,2,1,4,4,5,4,5,3,1,4,5,1,5,3,5,4,4,4,1,4,2,2,2,5,4,3,1,
4,4,3,4,2,1,1,5,3,3,2,5,3,1,2,2,4,1,4,1,5,1,1,2,5,2,2,5,2,4,4,3,4,1,3,3,5,4,5,4,5,5,5,5,5,4,4
,5,3,4,3,3,1,1,5,2,4,5,5,1,5,2,4,5,4,2,4,4,4,2,2,2,2,2,3,5,3,1,1,2,1,1,5,1,4,3,4,2,5,3,4,4,3,
5,5,5,4,1,3,4,4,2,2,1,4,1,2,1,2,1,5,5,3,4,1,3,2,1,4,5,1,5,5,1,2,3,4,2,1,4,1,4,2,3,3,2,4,1,4,1
,4,4,1,5,3,1,5,2,1,1,2,3,3,2,4,1,2,1,5,1,1,2,1,2,1,2,4,5,3,5,5,1,3,4,1,1,3,3,2,2,4,3,1,1,2,4,
1,1,1,5,4,2,4,3

------

Convert to:

First line: [2, 5, 3, 4, 4, 5, 3, 2, 3, 3, 2, 2, 4, 2, 5, 4, 1, 1, 4, 4, 5, 1, 2, 1, 5, 2, 1,
5, 1, 1, 1, 2, 4, 3, 3, 1, 4, 2, 3, 4, 5, 1, 2, 5, 1, 2, 2, 5, 2, 4, 4, 1, 4, 5, 4, 2, 1, 5, 
5, 3, 2, 1, 3, 2, 1, 4, 2, 5, 5, 5, 2, 3, 3, 5, 1, 1, 5, 3, 4, 2, 1, 4, 4, 5, 4, 5, 3, 1, 4, 
5, 1, 5, 3, 5, 4, 4, 4, 1, 4, 2, 2, 2, 5, 4, 3, 1, 4, 4, 3, 4, 2, 1, 1, 5, 3, 3, 2, 5, 3, 1, 
2, 2, 4, 1, 4, 1, 5, 1, 1, 2, 5, 2, 2, 5, 2, 4, 4, 3, 4, 1, 3, 3, 5, 4, 5, 4, 5, 5, 5, 5, 5, 
4, 4, 5, 3, 4, 3, 3, 1, 1, 5, 2, 4, 5, 5, 1, 5, 2, 4, 5, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 3, 5, 
3, 1, 1, 2, 1, 1, 5, 1, 4, 3, 4, 2, 5, 3, 4, 4, 3, 5, 5, 5, 4, 1, 3, 4, 4, 2, 2, 1, 4, 1, 2, 
1, 2, 1, 5, 5, 3, 4, 1, 3, 2, 1, 4, 5, 1, 5, 5, 1, 2, 3, 4, 2, 1, 4, 1, 4, 2, 3, 3, 2, 4, 1, 
4, 1, 4, 4, 1, 5, 3, 1, 5, 2, 1, 1, 2, 3, 3, 2, 4, 1, 2, 1, 5, 1, 1, 2, 1, 2, 1, 2, 4, 5, 3, 
5, 5, 1, 3, 4, 1, 1, 3, 3, 2, 2, 4, 3, 1, 1, 2, 4, 1, 1, 1, 5, 4, 2, 4, 3]

Last line: [2, 5, 3, 4, 4, 5, 3, 2, 3, 3, 2, 2, 4, 2, 5, 4, 1, 1, 4, 4, 5, 1, 2, 1, 5, 2, 1, 
5, 1, 1, 1, 2, 4, 3, 3, 1, 4, 2, 3, 4, 5, 1, 2, 5, 1, 2, 2, 5, 2, 4, 4, 1, 4, 5, 4, 2, 1, 5, 
5, 3, 2, 1, 3, 2, 1, 4, 2, 5, 5, 5, 2, 3, 3, 5, 1, 1, 5, 3, 4, 2, 1, 4, 4, 5, 4, 5, 3, 1, 4, 
5, 1, 5, 3, 5, 4, 4, 4, 1, 4, 2, 2, 2, 5, 4, 3, 1, 4, 4, 3, 4, 2, 1, 1, 5, 3, 3, 2, 5, 3, 1, 
2, 2, 4, 1, 4, 1, 5, 1, 1, 2, 5, 2, 2, 5, 2, 4, 4, 3, 4, 1, 3, 3, 5, 4, 5, 4, 5, 5, 5, 5, 5, 
4, 4, 5, 3, 4, 3, 3, 1, 1, 5, 2, 4, 5, 5, 1, 5, 2, 4, 5, 4, 2, 4, 4, 4, 2, 2, 2, 2, 2, 3, 5, 
3, 1, 1, 2, 1, 1, 5, 1, 4, 3, 4, 2, 5, 3, 4, 4, 3, 5, 5, 5, 4, 1, 3, 4, 4, 2, 2, 1, 4, 1, 2, 
1, 2, 1, 5, 5, 3, 4, 1, 3, 2, 1, 4, 5, 1, 5, 5, 1, 2, 3, 4, 2, 1, 4, 1, 4, 2, 3, 3, 2, 4, 1, 
4, 1, 4, 4, 1, 5, 3, 1, 5, 2, 1, 1, 2, 3, 3, 2, 4, 1, 2, 1, 5, 1, 1, 2, 1, 2, 1, 2, 4, 5, 3, 
5, 5, 1, 3, 4, 1, 1, 3, 3, 2, 2, 4, 3, 1, 1, 2, 4, 1, 1, 1, 5, 4, 2, 4, 3]

------

In [4]:
init_li = data[0]

(unique, counts) = np.unique(init_li, return_counts=True)
print(unique, counts)

[1 2 3 4 5] [69 60 45 67 59]

In [5]:
def pass_one_day(input_arr):
    output_arr = np.zeros_like(input_arr)
    for i in range(8):
        output_arr[i] = input_arr[i+1]
    output_arr[6] += input_arr[0]
    output_arr[8] += input_arr[0]
    return output_arr

In [6]:
fish_count = np.zeros(9).astype('int64')

for age, count in zip(unique, counts):
    fish_count[age] = count
print(fish_count)

after_day = 80

for i in range(after_day):
    fish_count = pass_one_day(fish_count)
    
print(fish_count)
print(f"Answer to Q1: {sum(fish_count)}")

[ 0 69 60 45 67 59  0  0  0]

[28641 37597 36137 42920 44569 46319 54829 23982 30393]

Answer to Q1: 345387

In [7]:
fish_count = np.zeros(9).astype('int64')

for age, count in zip(unique, counts):
    fish_count[age] = count
print(fish_count)

after_day = 256

for i in range(after_day):
    fish_count = pass_one_day(fish_count)
    
print(fish_count)
print(f"Answer to Q2: {sum(fish_count)}")

[ 0 69 60 45 67 59  0  0  0]

[141639703600 157315335343 170273085353 185236487147 204747801901
 218724675965 244825441756 118574737858 133108224213]

Answer to Q2: 1574445493136